pool:
  name:
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'
    publishJUnitResults: false
    checkStyleRunAnalysis: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: mywebapp'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: mywebapp
  condition: succeededOrFailed()

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: containerRegistryaz400
    repository: containerRegistryaz400

- script: |
   ls -ail
   cat kubernetes/deployment.yml
  displayName: 'Command Line Script'
