apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: containerregistryaz400
        image: containerregistryaz400.azurecr.io/containerregistryaz400:37
        ports:
        - containerPort: 80
